const PRODUCTS = [
  {
    id: 1,
    name: "Sony WH-1000XM5 Wireless Headphones",
    slug: "sony-wh1000xm5-headphones",
    category: "electronics",
    subcategory: "Audio",
    price: 349.99,
    originalPrice: 399.99,
    discount: 13,
    rating: 4.8,
    reviews: 2847,
    badge: "Best Seller",
    badgeColor: "bg-amber-500",
    inStock: true,
    stock: 45,
    sku: "SNY-WH1000-BLK",
    brand: "Sony",
    colors: ["#1a1a2e", "#f5f5f5", "#1e3a5f"],
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours battery life with quick charging.",
    features: ["Industry-leading noise cancellation", "30-hour battery life", "Multipoint connection", "Speak-to-Chat technology", "Premium comfort design"],
    specs: { "Driver Unit": "30mm", "Frequency Response": "4Hz-40,000Hz", "Battery Life": "30 hours", "Weight": "250g", "Connectivity": "Bluetooth 5.2" },
    shipping: "Free standard shipping (3-5 business days). Express shipping available at checkout.",
    relatedIds: [2, 3, 5]
  },
  {
    id: 2,
    name: "Nike Air Max 270 React Sneakers",
    slug: "nike-air-max-270-react",
    category: "fashion",
    subcategory: "Sneakers",
    price: 149.99,
    originalPrice: 189.99,
    discount: 21,
    rating: 4.6,
    reviews: 1523,
    badge: "Trending",
    badgeColor: "bg-rose-500",
    inStock: true,
    stock: 120,
    sku: "NKE-AM270-WHT",
    brand: "Nike",
    colors: ["#ffffff", "#1a1a2e", "#c0392b"],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80"
    ],
    description: "The Nike Air Max 270 React combines two of Nike's biggest technologies for an unreal underfoot experience. The Nike React foam provides a smooth, lightweight ride while the large Max Air unit adds plush cushioning.",
    features: ["React foam midsole", "Max Air 270 unit", "Breathable mesh upper", "Rubber outsole with flex grooves"],
    specs: { "Material": "Mesh/Synthetic", "Sole": "Rubber", "Closure": "Lace-up", "Weight": "310g (per shoe)" },
    shipping: "Free shipping on orders over $100. Easy 30-day returns.",
    relatedIds: [1, 4, 8]
  },
  {
    id: 3,
    name: "Apple Watch Series 9 GPS 45mm",
    slug: "apple-watch-series-9",
    category: "electronics",
    subcategory: "Wearables",
    price: 429.00,
    originalPrice: 499.00,
    discount: 14,
    rating: 4.9,
    reviews: 3201,
    badge: "New",
    badgeColor: "bg-emerald-500",
    inStock: true,
    stock: 28,
    sku: "APL-AWS9-45MM",
    brand: "Apple",
    colors: ["#1a1a2e", "#c0c0c0", "#e8d5b7"],
    images: [
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=800&q=80"
    ],
    description: "The most powerful Apple Watch yet. Features the new S9 SiP, a magical new way to use your watch without touching the screen, and a brighter display.",
    features: ["S9 SiP with custom Apple GPU", "Double Tap gesture", "Up to 18 hours battery", "Always-On Retina display", "Blood oxygen & ECG apps"],
    specs: { "Display": "45mm Always-On Retina LTPO OLED", "Chip": "S9 SiP", "Water Resistance": "50m", "Storage": "64GB", "Connectivity": "GPS, Bluetooth 5.3, Wi-Fi" },
    shipping: "Free express shipping. Gift wrapping available.",
    relatedIds: [1, 5, 6]
  },
  {
    id: 4,
    name: "Premium Leather Crossbody Bag",
    slug: "leather-crossbody-bag",
    category: "fashion",
    subcategory: "Bags",
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    rating: 4.5,
    reviews: 876,
    badge: "Sale",
    badgeColor: "bg-red-500",
    inStock: true,
    stock: 67,
    sku: "LTH-CRS-BRN",
    brand: "Artisan Co.",
    colors: ["#8b4513", "#1a1a2e", "#d2691e"],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Handcrafted from genuine full-grain leather, this crossbody bag combines timeless style with everyday functionality. Features adjustable strap and multiple compartments.",
    features: ["Genuine full-grain leather", "Adjustable strap", "Multiple compartments", "YKK zippers", "Antique brass hardware"],
    specs: { "Material": "Full-grain leather", "Dimensions": "9\" x 7\" x 3\"", "Strap Drop": "22-26 inches", "Weight": "450g", "Closure": "Zipper" },
    shipping: "Free standard shipping. Carefully packaged in a gift box.",
    relatedIds: [2, 7, 8]
  },
  {
    id: 5,
    name: "Samsung 65\" Neo QLED 4K Smart TV",
    slug: "samsung-65-neo-qled-4k",
    category: "electronics",
    subcategory: "Televisions",
    price: 1299.99,
    originalPrice: 1599.99,
    discount: 19,
    rating: 4.7,
    reviews: 1890,
    badge: "Hot Deal",
    badgeColor: "bg-orange-500",
    inStock: true,
    stock: 15,
    sku: "SAM-QN65-QN90C",
    brand: "Samsung",
    colors: ["#1a1a2e"],
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1461151304267-38535e780f79?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1558888401-3cc1de77652d?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Experience brilliant color and contrast with Neural Quantum Processor 4K. Quantum HDR 32x brings out details and color. Dolby Atmos and Object Tracking Sound for immersive audio.",
    features: ["Neural Quantum Processor 4K", "Quantum HDR 32x", "120Hz refresh rate", "Dolby Atmos & OTS+", "Smart TV with Tizen OS"],
    specs: { "Screen Size": "65 inches", "Resolution": "3840 x 2160", "HDR": "Quantum HDR 32x", "Refresh Rate": "120Hz", "Smart Platform": "Tizen" },
    shipping: "Free white-glove delivery and setup. Installation service available.",
    relatedIds: [1, 3, 6]
  },
  {
    id: 6,
    name: "Minimalist Wireless Charging Station",
    slug: "wireless-charging-station",
    category: "electronics",
    subcategory: "Accessories",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    rating: 4.4,
    reviews: 654,
    badge: null,
    badgeColor: null,
    inStock: true,
    stock: 200,
    sku: "WCS-3IN1-BLK",
    brand: "TechBase",
    colors: ["#1a1a2e", "#f5f5f5"],
    images: [
      "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1615526675159-e248c3021d3f?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Charge your phone, watch, and earbuds simultaneously with this elegant 3-in-1 wireless charging station. Sleek design complements any desk or nightstand.",
    features: ["3-in-1 charging", "15W fast charging", "Compatible with MagSafe", "LED indicator", "Anti-slip base"],
    specs: { "Input": "USB-C", "Output": "15W max", "Compatibility": "Qi-enabled devices", "Cable Length": "1.5m", "Weight": "320g" },
    shipping: "Free standard shipping. Ships within 24 hours.",
    relatedIds: [1, 3, 5]
  },
  {
    id: 7,
    name: "Scandinavian Modern Accent Chair",
    slug: "scandinavian-accent-chair",
    category: "home",
    subcategory: "Furniture",
    price: 349.00,
    originalPrice: 449.00,
    discount: 22,
    rating: 4.6,
    reviews: 432,
    badge: "Editor's Pick",
    badgeColor: "bg-violet-500",
    inStock: true,
    stock: 22,
    sku: "SCN-CHR-GRY",
    brand: "Nordic Living",
    colors: ["#808080", "#d4c5a9", "#2c3e50"],
    images: [
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Elevate your living space with this beautifully crafted Scandinavian accent chair. Features premium upholstery, solid wood legs, and ergonomic design for all-day comfort.",
    features: ["Premium fabric upholstery", "Solid oak legs", "High-density foam cushion", "Ergonomic back support", "Easy assembly"],
    specs: { "Material": "Fabric/Oak", "Dimensions": "28\" W x 30\" D x 32\" H", "Seat Height": "18 inches", "Weight Capacity": "300 lbs", "Assembly": "Required (15 min)" },
    shipping: "Free shipping. Assembly instructions included.",
    relatedIds: [8, 9, 10]
  },
  {
    id: 8,
    name: "Designer Aviator Sunglasses",
    slug: "designer-aviator-sunglasses",
    category: "fashion",
    subcategory: "Accessories",
    price: 159.00,
    originalPrice: 199.00,
    discount: 20,
    rating: 4.3,
    reviews: 987,
    badge: null,
    badgeColor: null,
    inStock: true,
    stock: 150,
    sku: "DZG-AVT-GLD",
    brand: "LuxeVision",
    colors: ["#ffd700", "#c0c0c0", "#1a1a2e"],
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Classic aviator design with modern UV400 protection lenses. Lightweight metal frame with adjustable nose pads for a perfect fit.",
    features: ["UV400 protection", "Polarized lenses", "Lightweight metal frame", "Adjustable nose pads", "Hard case included"],
    specs: { "Lens Width": "58mm", "Bridge": "14mm", "Temple": "140mm", "Material": "Stainless steel", "Lens": "Polarized CR-39" },
    shipping: "Free shipping with hard protective case.",
    relatedIds: [2, 4, 6]
  },
  {
    id: 9,
    name: "Smart Home Security Camera System",
    slug: "smart-security-camera-system",
    category: "electronics",
    subcategory: "Smart Home",
    price: 249.99,
    originalPrice: 329.99,
    discount: 24,
    rating: 4.5,
    reviews: 2156,
    badge: "Popular",
    badgeColor: "bg-blue-500",
    inStock: true,
    stock: 78,
    sku: "SHC-4CAM-WHT",
    brand: "SecureView",
    colors: ["#ffffff", "#1a1a2e"],
    images: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Complete 4-camera wireless security system with 2K resolution, night vision, two-way audio, and AI person detection. Works with Alexa and Google Home.",
    features: ["2K HD resolution", "Color night vision", "AI person detection", "Two-way audio", "Cloud & local storage"],
    specs: { "Resolution": "2K (2304x1296)", "Night Vision": "Up to 30ft", "Storage": "Cloud + microSD", "Power": "Rechargeable battery", "Connectivity": "Wi-Fi 6" },
    shipping: "Free shipping. Professional installation available.",
    relatedIds: [5, 6, 10]
  },
  {
    id: 10,
    name: "Handcrafted Ceramic Vase Set",
    slug: "handcrafted-ceramic-vase-set",
    category: "home",
    subcategory: "Decor",
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    rating: 4.7,
    reviews: 345,
    badge: "Handmade",
    badgeColor: "bg-teal-500",
    inStock: true,
    stock: 40,
    sku: "HCV-SET-3PC",
    brand: "Artisan Earth",
    colors: ["#f5f5dc", "#2c3e50", "#c0392b"],
    images: [
      "https://images.unsplash.com/photo-1612196808214-b7e239e5bbae?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581783898377-1c85bf93742a?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Set of 3 handcrafted ceramic vases in complementary shapes and sizes. Each piece is unique with a matte glaze finish. Perfect for fresh or dried flower arrangements.",
    features: ["Set of 3 vases", "Handcrafted ceramic", "Matte glaze finish", "Waterproof interior", "Unique variations"],
    specs: { "Material": "Ceramic", "Heights": "8\", 10\", 12\"", "Finish": "Matte glaze", "Origin": "Handmade", "Care": "Wipe clean" },
    shipping: "Carefully packaged with eco-friendly materials.",
    relatedIds: [7, 9, 11]
  },
  {
    id: 11,
    name: "Premium Yoga Mat - Extra Thick",
    slug: "premium-yoga-mat",
    category: "fashion",
    subcategory: "Activewear",
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    rating: 4.6,
    reviews: 1234,
    badge: null,
    badgeColor: null,
    inStock: true,
    stock: 300,
    sku: "YGM-PRO-6MM",
    brand: "ZenFit",
    colors: ["#2c3e50", "#8e44ad", "#27ae60"],
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2f608c1629?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Extra thick 6mm yoga mat made from eco-friendly TPE material. Non-slip texture on both sides provides excellent grip. Includes carrying strap.",
    features: ["6mm extra thick", "Non-slip dual texture", "Eco-friendly TPE", "Lightweight & portable", "Carrying strap included"],
    specs: { "Thickness": "6mm", "Dimensions": "72\" x 24\"", "Material": "TPE", "Weight": "900g", "Includes": "Carrying strap" },
    shipping: "Free standard shipping.",
    relatedIds: [8, 4, 12]
  },
  {
    id: 12,
    name: "Stainless Steel Water Bottle 32oz",
    slug: "stainless-steel-water-bottle",
    category: "home",
    subcategory: "Kitchen",
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    rating: 4.8,
    reviews: 4567,
    badge: "Top Rated",
    badgeColor: "bg-amber-500",
    inStock: true,
    stock: 500,
    sku: "SSB-32OZ-BLU",
    brand: "HydroMax",
    colors: ["#1e3a5f", "#1a1a2e", "#c0392b", "#27ae60"],
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1523362628755-013705e1d51e?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Double-wall vacuum insulated water bottle keeps drinks cold for 24 hours or hot for 12 hours. BPA-free with leak-proof lid.",
    features: ["24hr cold / 12hr hot", "BPA-free stainless steel", "Leak-proof lid", "Wide mouth opening", "Fits most cup holders"],
    specs: { "Capacity": "32oz (946ml)", "Material": "18/8 Stainless Steel", "Insulation": "Double-wall vacuum", "Weight": "340g", "Diameter": "3.5 inches" },
    shipping: "Free standard shipping.",
    relatedIds: [10, 11, 7]
  }
];

const CATEGORIES = [
  { id: "electronics", name: "Electronics", icon: "fas fa-bolt", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80", count: 4, description: "Latest gadgets and tech essentials" },
  { id: "fashion", name: "Fashion", icon: "fas fa-shirt", image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80", count: 4, description: "Trendy apparel and accessories" },
  { id: "home", name: "Home & Living", icon: "fas fa-couch", image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=600&q=80", count: 3, description: "Beautiful furniture and decor" },
  { id: "beauty", name: "Beauty & Care", icon: "fas fa-spa", image: "https://images.unsplash.com/photo-1596462502278-27bfdd403348?auto=format&fit=crop&w=600&q=80", count: 0, description: "Premium skincare and cosmetics" },
  { id: "sports", name: "Sports & Outdoors", icon: "fas fa-running", image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80", count: 0, description: "Gear for active lifestyles" },
  { id: "books", name: "Books & Media", icon: "fas fa-book", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80", count: 0, description: "Discover your next favorite read" }
];

const REVIEWS_DATA = [
  { id: 1, productId: 1, author: "Sarah J.", avatar: "SJ", rating: 5, date: "2 days ago", title: "Best headphones I've ever owned!", text: "The noise cancellation is incredible. I use these daily for work and the battery life is exactly as advertised. Worth every penny.", helpful: 42, verified: true },
  { id: 2, productId: 1, author: "Mike T.", avatar: "MT", rating: 4, date: "1 week ago", title: "Great sound, slightly tight fit", text: "Sound quality is phenomenal and the ANC is top-notch. Only complaint is they feel a bit tight after 3+ hours of use.", helpful: 18, verified: true },
  { id: 3, productId: 1, author: "Emily R.", avatar: "ER", rating: 5, date: "2 weeks ago", title: "Perfect for travel", text: "Used these on a 14-hour flight and they were comfortable the entire time. The carrying case is also very well made.", helpful: 31, verified: true },
  { id: 4, productId: 2, author: "James K.", avatar: "JK", rating: 5, date: "3 days ago", title: "Super comfortable and stylish", text: "These sneakers look even better in person. The React cushioning makes them incredibly comfortable for all-day wear.", helpful: 24, verified: true },
  { id: 5, productId: 2, author: "Lisa M.", avatar: "LM", rating: 4, date: "1 week ago", title: "Love the design", text: "Great looking shoes. I sized up half a size and they fit perfectly. The Air Max cushioning is noticeable.", helpful: 15, verified: false },
  { id: 6, productId: 3, author: "David W.", avatar: "DW", rating: 5, date: "5 days ago", title: "Double Tap is a game changer", text: "The new Double Tap gesture is incredibly intuitive. The display is noticeably brighter outdoors too. Best Apple Watch yet.", helpful: 67, verified: true },
  { id: 7, productId: 7, author: "Anna P.", avatar: "AP", rating: 5, date: "1 week ago", title: "Beautiful chair, great quality", text: "This chair is even more beautiful in person. The fabric is premium and the oak legs are solid. Assembly took about 10 minutes.", helpful: 28, verified: true },
  { id: 8, productId: 7, author: "Robert H.", avatar: "RH", rating: 4, date: "2 weeks ago", title: "Stylish and comfortable", text: "Perfect accent piece for our living room. Very comfortable for reading. Only wish it came in more color options.", helpful: 12, verified: true },
  { id: 9, productId: 12, author: "Chris L.", avatar: "CL", rating: 5, date: "3 days ago", title: "Keeps ice for a full day!", text: "I fill this with ice water in the morning and still have ice cubes at the end of the day. Best water bottle I've owned.", helpful: 89, verified: true },
  { id: 10, productId: 12, author: "Karen B.", avatar: "KB", rating: 5, date: "1 week ago", title: "Perfect size and quality", text: "The 32oz size is perfect for my daily needs. The wide mouth makes it easy to add ice cubes. Highly recommend!", helpful: 45, verified: true }
];

function getProductById(id) { return PRODUCTS.find(p => p.id === id); }
function getProductsByCategory(category) { return PRODUCTS.filter(p => p.category === category); }
function getRelatedProducts(ids) { return ids.map(id => getProductById(id)).filter(Boolean); }
function getProductReviews(productId) { return REVIEWS_DATA.filter(r => r.productId === productId); }
function getBestSellers() { return PRODUCTS.filter(p => p.rating >= 4.5).sort((a, b) => b.reviews - a.reviews).slice(0, 4); }
function getNewArrivals() { return PRODUCTS.filter(p => p.badge === "New" || p.badge === "Trending").slice(0, 4); }
function getSaleItems() { return PRODUCTS.filter(p => p.discount >= 20).sort((a, b) => b.discount - a.discount); }
function getAllBrands() { return [...new Set(PRODUCTS.map(p => p.brand))]; }
function getPriceRange() { return { min: Math.min(...PRODUCTS.map(p => p.price)), max: Math.max(...PRODUCTS.map(p => p.price)) }; }
